const recipes = [
    {
        name: "Борщ",
        description: "Классический украинский борщ",
        icon: "🍲",
        cook_time_minutes: 90,
        servings: 6,
        ingredients: [
            { name: "Свёкла", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Капуста", category: "Овощи", quantity: "300 г", optional: false },
            { name: "Картофель", category: "Овощи", quantity: "3 шт", optional: false },
            { name: "Морковь", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Лук", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Говядина", category: "Мясо", quantity: "400 г", optional: false },
            { name: "Томатная паста", category: "Соусы и приправы", quantity: "2 ст.л.", optional: false },
            { name: "Чеснок", category: "Овощи", quantity: "3 зуб.", optional: false },
        ],
        instructions: "1. Сварите бульон из говядины (1.5 часа). 2. Нарежьте картофель кубиками, добавьте в бульон. 3. Натрите свёклу и морковь, обжарьте с томатной пастой. 4. Нашинкуйте капусту, добавьте в бульон. 5. Добавьте зажарку, чеснок, специи. 6. Варите ещё 10 минут. Подавайте со сметаной.",
    },
    {
        name: "Оливье",
        description: "Новогодний салат с колбасой",
        icon: "🥗",
        cook_time_minutes: 40,
        servings: 4,
        ingredients: [
            { name: "Картофель", category: "Овощи", quantity: "3 шт", optional: false },
            { name: "Морковь", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Яйца", category: "Молочное", quantity: "4 шт", optional: false },
            { name: "Колбаса", category: "Мясо", quantity: "300 г", optional: false },
            { name: "Огурцы маринованные", category: "Соусы и приправы", quantity: "3 шт", optional: false },
            { name: "Горошек", category: "Бакалея", quantity: "1 банка", optional: false },
            { name: "Майонез", category: "Соусы и приправы", quantity: "150 г", optional: false },
        ],
        instructions: "1. Отварите картофель, морковь и яйца. 2. Нарежьте все ингредиенты кубиками. 3. Добавьте горошек. 4. Заправьте майонезом, посолите, перемешайте.",
    },
    {
        name: "Блины",
        description: "Тонкие блины на молоке",
        icon: "🥞",
        cook_time_minutes: 30,
        servings: 4,
        ingredients: [
            { name: "Молоко", category: "Молочное", quantity: "500 мл", optional: false },
            { name: "Яйца", category: "Молочное", quantity: "2 шт", optional: false },
            { name: "Мука", category: "Бакалея", quantity: "200 г", optional: false },
            { name: "Сахар", category: "Бакалея", quantity: "2 ст.л.", optional: false },
            { name: "Масло растительное", category: "Бакалея", quantity: "2 ст.л.", optional: false },
        ],
        instructions: "1. Взбейте яйца с сахаром. 2. Добавьте половину молока, перемешайте. 3. Постепенно всыпьте муку, размешивая до однородности. 4. Добавьте остаток молока и масло. 5. Жарьте на разогретой сковороде с двух сторон.",
    },
    {
        name: "Пельмени",
        description: "Домашние пельмени с мясом",
        icon: "🥟",
        cook_time_minutes: 60,
        servings: 4,
        ingredients: [
            { name: "Мука", category: "Бакалея", quantity: "400 г", optional: false },
            { name: "Яйца", category: "Молочное", quantity: "1 шт", optional: false },
            { name: "Вода", category: "Напитки", quantity: "150 мл", optional: false },
            { name: "Свинина", category: "Мясо", quantity: "300 г", optional: false },
            { name: "Говядина", category: "Мясо", quantity: "200 г", optional: false },
            { name: "Лук", category: "Овощи", quantity: "2 шт", optional: false },
        ],
        instructions: "1. Замесите тесто из муки, яйца и воды. 2. Прокрутите мясо и лук через мясорубку. 3. Раскатайте тесто, вырежьте кружки. 4. В каждый положите фарш, защипните. 5. Варите в кипящей воде 5-7 минут после всплытия.",
    },
    {
        name: "Курица с картошкой",
        description: "Запечённая курица с картофелем",
        icon: "🍗",
        cook_time_minutes: 60,
        servings: 4,
        ingredients: [
            { name: "Курица", category: "Мясо", quantity: "1 шт", optional: false },
            { name: "Картофель", category: "Овощи", quantity: "6 шт", optional: false },
            { name: "Майонез", category: "Соусы и приправы", quantity: "3 ст.л.", optional: false },
            { name: "Чеснок", category: "Овощи", quantity: "4 зуб.", optional: false },
        ],
        instructions: "1. Разрежьте курицу на порции. 2. Нарежьте картофель дольками. 3. Смешайте майонез с чесноком. 4. Выложите всё в форму, смажьте соусом. 5. Запекайте при 180°C 45 минут.",
    },
    {
        name: "Паста Карбонара",
        description: "Итальянская паста с беконом",
        icon: "🍝",
        cook_time_minutes: 25,
        servings: 2,
        ingredients: [
            { name: "Спагетти", category: "Бакалея", quantity: "200 г", optional: false },
            { name: "Бекон", category: "Мясо", quantity: "150 г", optional: false },
            { name: "Яйца", category: "Молочное", quantity: "2 шт", optional: false },
            { name: "Сыр", category: "Молочное", quantity: "50 г", optional: false },
        ],
        instructions: "1. Отварите спагетти. 2. Обжарьте бекон. 3. Смешайте яйца с тёртым сыром. 4. Соедините горячую пасту с беконом, влейте яичную смесь, быстро перемешайте.",
    },
    {
        name: "Греческий салат",
        description: "Свежий салат с фетой",
        icon: "🥗",
        cook_time_minutes: 15,
        servings: 2,
        ingredients: [
            { name: "Помидоры", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Огурцы", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Перец болгарский", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Сыр фета", category: "Молочное", quantity: "150 г", optional: false },
            { name: "Маслины", category: "Бакалея", quantity: "100 г", optional: false },
            { name: "Масло оливковое", category: "Соусы и приправы", quantity: "2 ст.л.", optional: false },
        ],
        instructions: "1. Нарежьте овощи крупными кусками. 2. Добавьте фету и маслины. 3. Заправьте оливковым маслом, посолите.",
    },
    {
        name: "Жареная картошка",
        description: "Картошка с луком на сковороде",
        icon: "🥔",
        cook_time_minutes: 30,
        servings: 3,
        ingredients: [
            { name: "Картофель", category: "Овощи", quantity: "6 шт", optional: false },
            { name: "Лук", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Масло растительное", category: "Бакалея", quantity: "3 ст.л.", optional: false },
        ],
        instructions: "1. Нарежьте картофель брусочками. 2. Разогрейте масло на сковороде. 3. Жарьте картофель на среднем огне 20 минут, помешивая. 4. Добавьте лук за 5 минут до готовности. Посолите.",
    },
    {
        name: "Сырники",
        description: "Творожные сырники со сметаной",
        icon: "🧀",
        cook_time_minutes: 25,
        servings: 3,
        ingredients: [
            { name: "Творог", category: "Молочное", quantity: "400 г", optional: false },
            { name: "Яйца", category: "Молочное", quantity: "1 шт", optional: false },
            { name: "Мука", category: "Бакалея", quantity: "3 ст.л.", optional: false },
            { name: "Сахар", category: "Бакалея", quantity: "2 ст.л.", optional: false },
            { name: "Сметана", category: "Молочное", quantity: "100 г", optional: true },
        ],
        instructions: "1. Смешайте творог, яйцо, муку и сахар. 2. Сформируйте шарики, обваляйте в муке. 3. Жарьте на масле по 3 минуты с каждой стороны. Подавайте со сметаной.",
    },
    {
        name: "Щи",
        description: "Русские щи из свежей капусты",
        icon: "🍲",
        cook_time_minutes: 60,
        servings: 4,
        ingredients: [
            { name: "Капуста", category: "Овощи", quantity: "400 г", optional: false },
            { name: "Картофель", category: "Овощи", quantity: "3 шт", optional: false },
            { name: "Морковь", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Лук", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Говядина", category: "Мясо", quantity: "300 г", optional: false },
        ],
        instructions: "1. Сварите бульон. 2. Добавьте нарезанный картофель. 3. Нашинкуйте капусту, добавьте в бульон. 4. Обжарьте лук и морковь, добавьте в щи. 5. Варите до готовности.",
    },
    {
        name: "Котлеты",
        description: "Домашние мясные котлеты",
        icon: "🥩",
        cook_time_minutes: 40,
        servings: 4,
        ingredients: [
            { name: "Фарш", category: "Мясо", quantity: "500 г", optional: false },
            { name: "Лук", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Хлеб", category: "Бакалея", quantity: "2 ломтика", optional: false },
            { name: "Яйца", category: "Молочное", quantity: "1 шт", optional: false },
        ],
        instructions: "1. Замочите хлеб в молоке. 2. Смешайте фарш, лук, хлеб и яйцо. 3. Сформируйте котлеты. 4. Обваляйте в муке, жарьте по 5 минут с каждой стороны.",
    },
    {
        name: "Омлет",
        description: "Пышный омлет с молоком",
        icon: "🍳",
        cook_time_minutes: 15,
        servings: 2,
        ingredients: [
            { name: "Яйца", category: "Молочное", quantity: "4 шт", optional: false },
            { name: "Молоко", category: "Молочное", quantity: "100 мл", optional: false },
            { name: "Масло сливочное", category: "Молочное", quantity: "20 г", optional: false },
        ],
        instructions: "1. Взбейте яйца с молоком и солью. 2. Вылейте на разогретую сковороду с маслом. 3. Готовьте под крышкой на медленном огне 7-10 минут.",
    },
    {
        name: "Винегрет",
        description: "Классический винегрет",
        icon: "🥗",
        cook_time_minutes: 30,
        servings: 4,
        ingredients: [
            { name: "Свёкла", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Картофель", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Морковь", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Огурцы маринованные", category: "Соусы и приправы", quantity: "2 шт", optional: false },
            { name: "Горошек", category: "Бакалея", quantity: "100 г", optional: false },
            { name: "Масло подсолнечное", category: "Соусы и приправы", quantity: "2 ст.л.", optional: false },
        ],
        instructions: "1. Отварите свёклу, картофель, морковь. 2. Нарежьте кубиками все овощи и огурцы. 3. Добавьте горошек. 4. Заправьте маслом, перемешайте.",
    },
    {
        name: "Макароны по-флотски",
        description: "Макароны с мясным фаршем",
        icon: "🍝",
        cook_time_minutes: 30,
        servings: 3,
        ingredients: [
            { name: "Макароны", category: "Бакалея", quantity: "300 г", optional: false },
            { name: "Фарш", category: "Мясо", quantity: "300 г", optional: false },
            { name: "Лук", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Томатная паста", category: "Соусы и приправы", quantity: "2 ст.л.", optional: true },
        ],
        instructions: "1. Отварите макароны. 2. Обжарьте фарш с луком. 3. Добавьте томатную пасту. 4. Смешайте с макаронами.",
    },
    {
        name: "Рассольник",
        description: "Суп с солёными огурцами",
        icon: "🍲",
        cook_time_minutes: 60,
        servings: 4,
        ingredients: [
            { name: "Картофель", category: "Овощи", quantity: "3 шт", optional: false },
            { name: "Огурцы маринованные", category: "Соусы и приправы", quantity: "3 шт", optional: false },
            { name: "Перловка", category: "Бакалея", quantity: "100 г", optional: false },
            { name: "Морковь", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Лук", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Говядина", category: "Мясо", quantity: "300 г", optional: false },
        ],
        instructions: "1. Сварите бульон с перловкой. 2. Добавьте картофель. 3. Обжарьте лук, морковь и нарезанные огурцы. 4. Добавьте зажарку в суп, варите 10 минут.",
    },
    {
        name: "Тушёная капуста",
        description: "Капуста тушёная с мясом",
        icon: "🥬",
        cook_time_minutes: 50,
        servings: 3,
        ingredients: [
            { name: "Капуста", category: "Овощи", quantity: "500 г", optional: false },
            { name: "Свинина", category: "Мясо", quantity: "200 г", optional: false },
            { name: "Морковь", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Томатная паста", category: "Соусы и приправы", quantity: "1 ст.л.", optional: true },
        ],
        instructions: "1. Нарежьте мясо, обжарьте. 2. Добавьте морковь, лук. 3. Нашинкуйте капусту, добавьте к мясу. 4. Тушите под крышкой 30 минут.",
    },
    {
        name: "Жареная рыба",
        description: "Рыба жареная в муке",
        icon: "🐟",
        cook_time_minutes: 25,
        servings: 2,
        ingredients: [
            { name: "Рыба", category: "Рыба", quantity: "4 стейка", optional: false },
            { name: "Мука", category: "Бакалея", quantity: "100 г", optional: false },
            { name: "Масло растительное", category: "Бакалея", quantity: "3 ст.л.", optional: false },
            { name: "Лимон", category: "Фрукты", quantity: "0.5 шт", optional: true },
        ],
        instructions: "1. Обваляйте рыбу в муке с солью. 2. Жарьте на масле по 4 минуты с каждой стороны. 3. Сбрызните лимоном.",
    },
    {
        name: "Плов",
        description: "Узбекский плов с бараниной",
        icon: "🍚",
        cook_time_minutes: 90,
        servings: 6,
        ingredients: [
            { name: "Рис", category: "Бакалея", quantity: "400 г", optional: false },
            { name: "Баранина", category: "Мясо", quantity: "500 г", optional: false },
            { name: "Морковь", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Лук", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Чеснок", category: "Овощи", quantity: "1 головка", optional: false },
        ],
        instructions: "1. Обжарьте мясо. 2. Добавьте лук и морковь (зирвак). 3. Залейте водой, тушите 30 мин. 4. Добавьте рис и чеснок. 5. Готовьте на медленном огне, пока рис не впитает воду.",
    },
    {
        name: "Грибы жареные",
        description: "Жареные грибы с картошкой",
        icon: "🍄",
        cook_time_minutes: 35,
        servings: 3,
        ingredients: [
            { name: "Грибы", category: "Овощи", quantity: "300 г", optional: false },
            { name: "Картофель", category: "Овощи", quantity: "4 шт", optional: false },
            { name: "Лук", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Сметана", category: "Молочное", quantity: "2 ст.л.", optional: true },
        ],
        instructions: "1. Нарежьте грибы и картофель. 2. Обжарьте картофель до полуготовности. 3. Добавьте грибы и лук. 4. Жарьте до готовности. По желанию добавьте сметану.",
    },
    {
        name: "Каша овсяная",
        description: "Овсяная каша с фруктами",
        icon: "🥣",
        cook_time_minutes: 15,
        servings: 2,
        ingredients: [
            { name: "Овсянка", category: "Бакалея", quantity: "100 г", optional: false },
            { name: "Молоко", category: "Молочное", quantity: "200 мл", optional: false },
            { name: "Сахар", category: "Бакалея", quantity: "1 ст.л.", optional: true },
            { name: "Масло сливочное", category: "Молочное", quantity: "10 г", optional: true },
        ],
        instructions: "1. Залейте овсянку молоком. 2. Доведите до кипения. 3. Варите 5 минут, помешивая. 4. Добавьте сахар и масло.",
    },
    {
        name: "Шарлотка",
        description: "Яблочный пирог",
        icon: "🍰",
        cook_time_minutes: 50,
        servings: 6,
        ingredients: [
            { name: "Яблоки", category: "Фрукты", quantity: "4 шт", optional: false },
            { name: "Яйца", category: "Молочное", quantity: "4 шт", optional: false },
            { name: "Мука", category: "Бакалея", quantity: "200 г", optional: false },
            { name: "Сахар", category: "Бакалея", quantity: "150 г", optional: false },
        ],
        instructions: "1. Взбейте яйца с сахаром. 2. Добавьте муку. 3. Нарежьте яблоки. 4. Выложите яблоки в форму, залейте тестом. 5. Выпекайте при 180°C 35 минут.",
    },
    {
        name: "Минестроне",
        description: "Итальянский овощной суп",
        icon: "🍲",
        cook_time_minutes: 40,
        servings: 4,
        ingredients: [
            { name: "Картофель", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Морковь", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Помидоры", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Кабачок", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Макароны", category: "Бакалея", quantity: "100 г", optional: false },
        ],
        instructions: "1. Нарежьте все овощи. 2. Сварите бульон, добавьте картофель и морковь. 3. Через 10 мин добавьте остальные овощи и макароны. 4. Варите до готовности.",
    },
    {
        name: "Куриный суп",
        description: "Лёгкий суп с курицей и лапшой",
        icon: "🍲",
        cook_time_minutes: 45,
        servings: 4,
        ingredients: [
            { name: "Курица", category: "Мясо", quantity: "300 г", optional: false },
            { name: "Картофель", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Морковь", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Лапша", category: "Бакалея", quantity: "100 г", optional: false },
        ],
        instructions: "1. Сварите куриный бульон. 2. Добавьте картофель и морковь. 3. Через 15 минут добавьте лапшу. 4. Варите ещё 5 минут.",
    },
    {
        name: "Голубцы",
        description: "Голубцы в сметанном соусе",
        icon: "🥬",
        cook_time_minutes: 70,
        servings: 4,
        ingredients: [
            { name: "Капуста", category: "Овощи", quantity: "1 кочан", optional: false },
            { name: "Фарш", category: "Мясо", quantity: "400 г", optional: false },
            { name: "Рис", category: "Бакалея", quantity: "100 г", optional: false },
            { name: "Морковь", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Сметана", category: "Молочное", quantity: "200 г", optional: false },
        ],
        instructions: "1. Отварите капусту, разберите на листья. 2. Смешайте фарш с рисом. 3. Заверните фарш в листья. 4. Обжарьте морковь, добавьте сметану. 5. Тушите голубцы в соусе 40 минут.",
    },
    {
        name: "Тёплый салат",
        description: "Салат с курицей и овощами",
        icon: "🥗",
        cook_time_minutes: 25,
        servings: 2,
        ingredients: [
            { name: "Курица", category: "Мясо", quantity: "200 г", optional: false },
            { name: "Помидоры", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Салат айсберг", category: "Овощи", quantity: "100 г", optional: false },
            { name: "Сыр", category: "Молочное", quantity: "50 г", optional: true },
        ],
        instructions: "1. Обжарьте курицу кусочками. 2. Нарежьте овощи. 3. Выложите салат, сверху курицу и овощи. 4. Посыпьте сыром.",
    },
    {
        name: "Картофельная запеканка",
        description: "Запеканка с мясом и картофелем",
        icon: "🥘",
        cook_time_minutes: 60,
        servings: 4,
        ingredients: [
            { name: "Картофель", category: "Овощи", quantity: "5 шт", optional: false },
            { name: "Фарш", category: "Мясо", quantity: "300 г", optional: false },
            { name: "Сыр", category: "Молочное", quantity: "100 г", optional: false },
            { name: "Молоко", category: "Молочное", quantity: "100 мл", optional: false },
        ],
        instructions: "1. Отварите картофель, сделайте пюре. 2. Обжарьте фарш. 3. Выложите слоями: пюре, фарш, пюре. 4. Посыпьте сыром. 5. Запекайте при 180°C 25 минут.",
    },
    {
        name: "Уха",
        description: "Рыбный суп из сёмги",
        icon: "🍲",
        cook_time_minutes: 50,
        servings: 4,
        ingredients: [
            { name: "Рыба", category: "Рыба", quantity: "400 г", optional: false },
            { name: "Картофель", category: "Овощи", quantity: "3 шт", optional: false },
            { name: "Морковь", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Лук", category: "Овощи", quantity: "1 шт", optional: false },
        ],
        instructions: "1. Сварите рыбный бульон. 2. Добавьте картофель и морковь. 3. Обжарьте лук, добавьте в суп. 4. Варите до готовности картофеля.",
    },
    {
        name: "Оладьи",
        description: "Пышные оладьи на кефире",
        icon: "🥞",
        cook_time_minutes: 25,
        servings: 3,
        ingredients: [
            { name: "Кефир", category: "Молочное", quantity: "250 мл", optional: false },
            { name: "Мука", category: "Бакалея", quantity: "200 г", optional: false },
            { name: "Яйца", category: "Молочное", quantity: "1 шт", optional: false },
            { name: "Сахар", category: "Бакалея", quantity: "2 ст.л.", optional: false },
        ],
        instructions: "1. Смешайте кефир, яйцо, сахар. 2. Постепенно добавьте муку. 3. Жарьте на разогретой сковороде с двух сторон.",
    },
    {
        name: "Творожная запеканка",
        description: "Запеканка из творога",
        icon: "🧁",
        cook_time_minutes: 50,
        servings: 4,
        ingredients: [
            { name: "Творог", category: "Молочное", quantity: "500 г", optional: false },
            { name: "Яйца", category: "Молочное", quantity: "2 шт", optional: false },
            { name: "Мука", category: "Бакалея", quantity: "3 ст.л.", optional: false },
            { name: "Сахар", category: "Бакалея", quantity: "4 ст.л.", optional: false },
        ],
        instructions: "1. Смешайте творог, яйца, муку, сахар. 2. Выложите в форму. 3. Выпекайте при 180°C 35 минут.",
    },
    {
        name: "Овощное рагу",
        description: "Рагу из сезонных овощей",
        icon: "🥘",
        cook_time_minutes: 45,
        servings: 3,
        ingredients: [
            { name: "Картофель", category: "Овощи", quantity: "3 шт", optional: false },
            { name: "Кабачок", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Помидоры", category: "Овощи", quantity: "2 шт", optional: false },
            { name: "Морковь", category: "Овощи", quantity: "1 шт", optional: false },
            { name: "Лук", category: "Овощи", quantity: "1 шт", optional: false },
        ],
        instructions: "1. Нарежьте все овощи. 2. Обжарьте лук и морковь. 3. Добавьте картофель, тушите 15 мин. 4. Добавьте кабачок и помидоры. 5. Тушите ещё 15 минут.",
    },
];

export default recipes;